#!/usr/bin/bash

## CONSTANTS
# Start of the string |     1-3 numbers with dots in between x4     | 1-5 number port
IPADRESS_PORT_REGEX="^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{1,5}$"
IGNORED_ADB_LINES="List|of|devices|attached|device$"

## COLORS
NC='\033[0m' # No Color
ERROR='\033[0;31m[ERROR]'
WARNING='\033[0;33m[WARNING]'
INFO='\033[2;37m[INFO]'
ADB='\033[2;37m[ADB]'
INPUT='\033[1;34m'

## FUNCTIONS
find_mdns() {
    device_uris=()
    device_names=()
    local i=0
    local found_device=0
    for line in $(avahi-browse --terminate --resolve --parsable --no-db-lookup _adb-tls-connect._tcp); do
        # Device name is on the next line so we extract it here
        if (( found_device > 0 )); then
            # Remove Suffix '"'
            local name="${line%\"}"
            # Remove prefix '"name='
            name="${name#\"name=}"
            device_names+=($name)
            found_device=0
            (( i++ ))
        fi

        if [[ $line != =* ]]; then
            continue
        fi

        # Seperate by ;
        IFS=';'; fields=($line); unset IFS;
        local uri="${fields[7]}:${fields[8]}"

        # Device already in list
        if [[ " ${device_uris[*]} " =~ [[:space:]]${uri}[[:space:]] ]]; then
            continue
        fi

        device_uris+=($uri)
        found_device=1
    done
}

connect_to() {
    echo -e "${NC}These devices were found:"

    arraylength=${#device_uris[@]}
    for (( i=0; i<${arraylength}; i++ ));
    do
        echo "$i: ${device_names[$i]} (${device_uris[$i]})"
    done

    echo -e "$i: Enter IP-Adress manually"

    echo -en "${INPUT}Select the device to connect to [0]: $NC"
    read device

    if (( device > i )); then
        echo -e "$WARNING Invalid device selector"
        connect_to
        return
    elif (( device == i )); then
        connect_ip
        return
    fi

    local name=${device_names[$device]}
    local uri=${device_uris[$device]}
    echo -e "$INFO Attempting to connect to $name ($uri)"
    local adb_result=$(adb connect $uri)
    echo -e "$ADB $adb_result"

    # Note: adb exits with 0 even if the connection fails,
    # so I'm checking its output
    if [[ $adb_result =~ connected ]]; then
        echo -e "$INFO Successfully conected to $name ($uri)"
        return
    fi
    echo -e "$ERROR Failed to connect to $name ($uri)"
    connect_to
    return
}

connect_ip() {
    echo -en "${INPUT}Enter 'ADDR:PORT': $NC"
    read uri
    if [[ $answer =~ $IPADRESS_PORT_REGEX ]]; then
        adb_result="$(adb connect $uri)"
        echo -e "$INFO $adb_result"
        if [[ $adb_result =~ connected ]]; then
            echo -e "$INFO Successfully connected to $uri"
        else
            echo -e "$ERROR Failed to connect to '$uri'"
            connect_to
            return
        fi
    else
        echo -e "$ERROR Invalid IP-Adress and/or Port"
        connect_to
        return
    fi
}

echo -e "$INFO Searching for devices using mdns..."
find_mdns

connect_to

echo -en "$NC"

