#!/usr/bin/bash

# Just a file where i try out random stuff

IPADRESS_PORT_REGEX="^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{1,5}$"
IGNORED_LINES="List|of|devices|attached|device$"

all_connected() {
    local num_all=0
    for line in $(adb devices); do
        # Not a USB device
        if [[ $line =~ $IGNORED_LINES ]]; then
            continue
        fi
        (( num_all++ ))
    done

    echo $num_all
    return $num_all
}
all_connected
if (( $(all_connected) > 1 )); then
	echo "multiple devices"
fi
