#!/usr/bin/bash

# Just a file where i try out random stuff

trap "stop" EXIT

stop() {
    echo "Stopping"
    exit 0 # Will this loop? --> No, it didn't :)
}

echo "Endo of PRogram"
exit 0
echo "Something else"
