#!/usr/bin/bash

stream_audio() {
    scrcpy --require-audio --no-video --no-window --no-control $args
}

read -p "Enter 'addr:port' to use WiFi otherwise USB is used: " answer

# Start of the string |     1-3 numbers with dots in between x4     | 1-5 number port
IPADRESS_PORT_REGEX="^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{1,5}$"

if [[ $answer =~ $IPADRESS_PORT_REGEX ]]; then
    adb connect $answer
    args="-e"
else
    args="-d"
fi
stream_audio
