#!/usr/bin/bash

## CONSTANTS
# Start of the string |     1-3 numbers with dots in between x4     | 1-5 number port
IPADRESS_PORT_REGEX="^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{1,5}$"
IGNORED_ADB_LINES="List|of|devices|attached|device$"

## COLORS
NC='\033[0m' # No Color
ERROR='\033[0;31m[ERROR]'
WARNING='\033[0;33m[WARNING]'
INFO='\033[2;37m[INFO]'
INPUT='\033[1;34m'

## FUNCTIONS
stream_audio() {
    scrcpy --require-audio --no-video --no-window --no-control $args
}

connect_new() {
    echo -en "${NC}1: Find device via MDNS \n2: Connect directly via IP \n3: It's already connected \n${INPUT}Choose an option: $NC"
    read answer
    case $answer in
        1)
            connect_mdns
        ;;
        2)
            connect_ip
        ;;
        3)
            if (( $(all_connected) > 0 )); then
                echo -e "$INFO New devices detected..."
                main
                return
            fi
            echo -e "$WARNING Unable to find any connected devices. Run 'adb devices' to check yourself"
            connect_new
            return
        ;;
        *)
            echo -e "$WARNING Invalid option"
            connect_new
            return
        ;;
    esac
}

connect_mdns() {
    local device_uris=()
    local device_names=()
    local i=0
    local found_device=0
    echo -e "${NC}These devices were found:"
    for line in $(avahi-browse --terminate --resolve --parsable --no-db-lookup _adb-tls-connect._tcp); do
        # Device name is on the next line so we extract it here
        if (( found_device > 0 )); then
            # Remove Suffix '"'
            local name="${line%\"}"
            # Remove prefix '"name='
            name="${name#\"name=}"
            device_names+=($name)
            found_device=0
            echo "$i: $name"
            (( i++ ))
        fi

        if [[ $line != =* ]]; then
            continue
        fi

        # Seperate by ;
        IFS=';'; fields=($line); unset IFS;
        local uri="${fields[7]}:${fields[8]}"

        if [[ " ${device_uris[*]} " =~ [[:space:]]${uri}[[:space:]] ]]; then
            continue
        fi

        device_uris+=($uri)
        found_device=1
    done

    echo -en "${INPUT}Select the device to connect to [0, 1, 2, ...]: $NC"
    read device

    local uri=${device_uris[$device]}
    echo -e "$INFO Attempting to connect to $uri"
    local adb_result=$(adb connect $uri)
    echo -e "$INFO $adb_result"

    # Note: adb exits with 0 even if the connection fails,
    # so I'm checking its output
    if [[ $adb_result =~ connected ]]; then
        echo -e "$INFO Successfully conected to $uri"
        args="--serial=$uri"
        return
    fi
    echo -e "$ERROR Failed to connect to $uri"
    connect_new
    return
}

connect_ip() {
    echo -en "${INPUT}Enter 'ADDR:PORT': $NC"
    read uri
    if [[ $answer =~ $IPADRESS_PORT_REGEX ]]; then
        adb_result="$(adb connect $uri)"
        echo -e "$INFO $adb_result"
        if [[ $adb_result =~ connected ]]; then
            echo -e "$INFO Successfully connected to $uri"
        else
            echo -e "$ERROR Failed to connect to '$uri'"
            connect_new
            return
        fi
        args="--serial=$uri"
    else
        echo -e "$ERROR Invalid IP-Adress and/or Port"
        connect_new
        return
    fi
}

all_connected() {
    local num_all=0
    for line in $(adb devices); do
        # Not a USB device
        if [[ $line =~ $IGNORED_ADB_LINES ]]; then
            continue
        fi
        (( num_all++ ))
    done

    echo $num_all
    return $num_all
}

usb_connected() {
    local num_usb=0
    for line in $(adb devices); do
        # Not a USB device
        if [[ $line =~ $IGNORED_ADB_LINES || $line =~ $IPADRESS_PORT_REGEX ]]; then
            continue
        fi
        (( num_usb++ ))
    done

    echo $num_usb
    return $num_usb
}

tcp_connected() {
local num_ip=0
    for line in $(adb devices); do
        # TCP/IP device
        if [[ $line =~ $IPADRESS_PORT_REGEX ]]; then
            (( num_ip++ ))
        fi
    done

    echo $num_ip
    return $num_ip
}

choose_device() {
    echo -e "${NC}These devices are currently connected:"
    local i=0
    local adb_devices=()
    for line in $(adb devices); do
        if [[ $line =~ $IGNORED_ADB_LINES ]]; then
            continue
        fi
        echo "$i: $line"
        adb_devices+=($line)
        (( i++ ))
    done
    echo "$i: Connect new device"
    echo -en "${INPUT}Select the device to clone audio from [0, 1, 2, ...]: $NC"
    read device
    if (( device > i )); then
        echo -e "$WARNING Invalid device selector"
        choose_device
        return
    elif (( device == i )); then
        connect_new
        return
    fi
    args="--serial=${adb_devices[$device]}"
}

main() {
    if (( $(all_connected) > 1 )); then
        echo -e "$INFO Multiple devices found..."
        choose_device
    elif (( $(usb_connected) == 1 )); then
        echo -e "$INFO USB device found..."
        args="--select-usb"
    elif (( $(tcp_connected) == 1 )); then
        echo -e "$INFO TCP/IP device found..."
        args="--select-tcpip"
    else
        echo -e "$INFO No devices found..."
        connect_new
    fi
}

main

#Reset color before running scrcpy
echo -en "$NC"

stream_audio
